[package]
name = "Swarm-Wallpaper"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.2", features = ["derive"] }
glam = "0.30.5"
pollster = "0.4.0"
wgpu = "26.0.1"
winit = "0.30.12"
